/**
 * @file
 * @brief Generated XER binary transfer structs.
 *
 * Generated by php/generate_xfer_struct.php.
 * Source schema: examples/example_serialize_generated_schema.php
 * Schema version: 2026-05-27T13:29:13+00:00
 */

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <xer/serialize.h>

namespace xer_example {

struct generated_record {
    std::uint32_t id{};
    std::u8string name{};
    std::vector<std::byte> payload{};
    std::map<std::u8string, double> scores{};
    std::vector<std::uint16_t> history{};
    std::array<std::uint32_t, 4> fixed{};
};

inline constexpr char generated_record_xfer_schema_generated_at[] = "2026-05-27T13:29:13+00:00";

template<class Archive>
auto xfer(Archive& ar, generated_record& value) -> xer::result<void>
{
    if (auto r = ar(value.id); !r) {
        return r;
    }
    if (auto r = ar(value.name); !r) {
        return r;
    }
    if (auto r = ar(value.payload); !r) {
        return r;
    }
    if (auto r = ar(value.scores); !r) {
        return r;
    }
    if (auto r = ar(value.history); !r) {
        return r;
    }
    if (auto r = ar(value.fixed); !r) {
        return r;
    }

    return {};
}

} // namespace xer_example
