/**
 * @file
 * @brief Generated XER binary transfer structs.
 *
 * Generated by php/generate_xfer_struct.php.
 * Source schema: examples/example_serialize_generated_multi_schema.php
 * Schema version: 2026-05-27T00:00:00+00:00
 */

#pragma once

#include <array>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <xer/serialize.h>

namespace xer_example_multi {

struct packet_header {
    std::uint16_t version{};
    std::uint16_t kind{};
    std::uint32_t sequence{};
};

inline constexpr char packet_header_xfer_schema_generated_at[] = "2026-05-27T00:00:00+00:00";

template<class Archive>
auto xfer(Archive& ar, packet_header& value) -> xer::result<void>
{
    if (auto r = ar(value.version); !r) {
        return r;
    }
    if (auto r = ar(value.kind); !r) {
        return r;
    }
    if (auto r = ar(value.sequence); !r) {
        return r;
    }

    return {};
}


struct sensor_sample {
    std::uint32_t id{};
    std::u8string name{};
    std::vector<float> values{};
    std::map<std::u8string, double> calibration{};
    std::array<std::uint8_t, 8> raw{};
};

inline constexpr char sensor_sample_xfer_schema_generated_at[] = "2026-05-27T00:00:00+00:00";

template<class Archive>
auto xfer(Archive& ar, sensor_sample& value) -> xer::result<void>
{
    if (auto r = ar(value.id); !r) {
        return r;
    }
    if (auto r = ar(value.name); !r) {
        return r;
    }
    if (auto r = ar(value.values); !r) {
        return r;
    }
    if (auto r = ar(value.calibration); !r) {
        return r;
    }
    if (auto r = ar(value.raw); !r) {
        return r;
    }

    return {};
}

} // namespace xer_example_multi
